XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
S--------X-----------------X--------------X--X
X--XXXX--X--XXXXXXXXXXXXX--X--XXXX--XXXX--X--X
X--X-----X--X--------X--X--X-----X--X--X--X--X
X--XXXXXXX--X--XXXX--X--X--XXXXXXX--X--X--X--X
X--X-----X--X--X-----X--X-----------X--X-----X
X--X--X--X--X--X--XXXX--XXXXXXXXXX--X--XXXX--X
X-----X-----X--X--X--X--------------X--------X
XXXXXXXXXXXXX--X--X--XXXX--X--XXXXXXXXXXXXX--X
X-----------X--X-----X-----X-----X-----X-----X
X--XXXXXXX--X--XXXX--XXXX--XXXX--XXXX--X--XXXX
X--X-----X--X--X--X--------X--X--------X-----X
X--X--X--XXXX--X--XXXXXXX--X--X--XXXXXXXXXX--X
X-----X--------X--X--X-----X-----X-----------X
XXXX--XXXXXXX--X--X--X--XXXXXXXXXX--XXXXXXXXXX
X--X-----X-----X-----X-----------X-----X-----X
X--XXXX--X--XXXX--XXXXXXXXXXXXXXXXXXX--X--X--X
X--------X-----X--X-----X-----------X-----X--X
XXXXXXXXXX--XXXX--XXXX--X--XXXXXXX--XXXXXXX--X
X--------X--X--------X--X--------X--X--------X
X--XXXX--X--X--XXXX--X--XXXXXXXXXX--X--XXXX--X
X-----X-----X--X-----X-----X--------X--X-----X
XXXX--XXXXXXX--XXXXXXXXXX--X--XXXXXXX--X--XXXX
X-----X-----X-----X-----X--------X-----X--X--X
X--XXXX--XXXXXXX--X--X--XXXX--X--XXXX--X--X--X
X--X--------------X--X-----X--X--------X-----X
X--XXXX--XXXXXXXXXX--XXXX--X--XXXXXXX--XXXXXXX
X--------X-----------X-----X--X-----X--X-----X
XXXXXXXXXX--XXXXXXXXXX--XXXX--XXXX--X--X--X--X
X--------------------X--------------X-----X--F
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
