$key_move_up = "w"
$key_move_left = "a"
$key_move_right = "d"
$key_move_down = "x"
$key_move_up_left = "q"
$key_move_up_right = "e"
$key_move_down_left = "z"
$key_move_down_right = "c"
$key_move_nowhere = "s"

$key_down_stairs = ">"
$key_up_stairs = "<"

$key_open_logs = "l"
$key_open_help = "h"
$key_open_keybindings = "K"
$key_inspect_surroundings = "M"

$key_pickup_items = "SPACE"
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
