$key_move_up = "w"
$key_move_left = "a"
$key_move_right = "d"
$key_move_down = "x"
$key_move_up_left = "q"
$key_move_up_right = "e"
$key_move_down_left = "z"
$key_move_down_right = "c"
$key_move_nowhere = "s"

$key_down_stairs = ">"
$key_up_stairs = "<"

$key_open_logs = "L"
$key_open_help = "H"
$key_open_keybindings = "K"
$key_inspect_surroundings = "M"
$key_open_inventory = "I"
$key_open_equipment = "E"
$key_read_more = "r"

$key_pickup_items = "SPACE"
$key_confirm = "RETURN"
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
$key_ = ""
